language: php

php:
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
  - php: nightly

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

install:
  - composer update $COMPOSER_OPTS

script:
  - rm -fv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - vendor/bin/phpunit
  - vendor/bin/composer-require-checker

jobs:
  include:
    - stage: coverage
      script:
        - vendor/bin/phpunit --coverage-clover=coverage.xml
        - bash <(curl -s https://codecov.io/bash)

git:
  depth: 5

group: travis_latest
